version: '3.8'
tasks:
  build:
    cmds:
      - go build -o ./build/s3mounter{{exeExt}} .
    sources:
      - ./**/*.go
    generates:
      - ./build/s3mounter{{exeExt}}
  install:
    cmds:
      - go install .
    sources:
      - ./**/*.go
